version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - export GO111MODULE=on
      - echo Build App started on `date`
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo -ldflags '-w' -o main *.go
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t xubio/sueldos/autenticacion .
      - docker tag xubio/sueldos/autenticacion:$IMAGE_TAG $IMAGE_REPO_NAME.dkr.ecr.$AWS_REGION.amazonaws.com/xubio/sueldos/autenticacion:$IMAGE_TAG     
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG